'root':
  setup_env_script: '/afs/cern.ch/work/a/afornara/public/23_03_23/newpy/miniconda/bin/activate'
  generations:
    1: # Make the particle distribution
      job_folder: 'master_jobs/000_make_part_distribution'
      job_executable: 000_make_distrib.py # has to be a python file
      files_to_clone: # relative to the template folder
        - clean_it.sh
      run_on: 'local_pc'
    2: # Launch the tracking
      job_folder: 'master_jobs/002_tracking_job'
      job_executable: 000_track.py # has to be a python file
      files_to_clone: # relative to the template folder
        - clean_it.sh
        - utilsaf.py
      run_on: 'htc_GPU' #'htc','htc_GPU'
      htc_job_flavor: 'tomorrow' # optional parameter to define job flavor, default is espress
  use_yaml_children: False
  # first generation
  children:
    '000_create_distributions':
      children:
        '000_tracking':
          xline_json :    '../../line_bb_for_tracking.json'
          # distribution in the normalized xy space
          particle_file:  '../transverse_distr.parquet'
          n_turns: 1000000
    '001_create_distributions':
      children:
          '000_tracking':
            xline_json :    '../../line_bb_for_tracking.json'
            # distribution in the normalized xy space
            particle_file:  '../transverse_distr.parquet'
            n_turns: 1000000
ph_noise : 8.0e-6
a_noise : 1.0e-11
n_turns : 1000000