# Description of the xline
xline_json :    '../001_machine_model/line_bb_for_tracking.json'

# distribution in the normalized xy space
particle_file:  '../000_make_part_distribution/particles/000.parquet'

# tracking
n_turns    :    100     # number of turns to track

log_file   :    'tree_maker.log'