# Running on local pc
bash /afs/cern.ch/work/a/afornara/public/xmask/example_DA_study/noise_master_study/scans/example_HL_tunescan/base_collider/xtrack_0000/run.sh &
bash /afs/cern.ch/work/a/afornara/public/xmask/example_DA_study/noise_master_study/scans/example_HL_tunescan/base_collider/xtrack_0001/run.sh &
bash /afs/cern.ch/work/a/afornara/public/xmask/example_DA_study/noise_master_study/scans/example_HL_tunescan/base_collider/xtrack_0002/run.sh &
bash /afs/cern.ch/work/a/afornara/public/xmask/example_DA_study/noise_master_study/scans/example_HL_tunescan/base_collider/xtrack_0003/run.sh &
bash /afs/cern.ch/work/a/afornara/public/xmask/example_DA_study/noise_master_study/scans/example_HL_tunescan/base_collider/xtrack_0004/run.sh &
bash /afs/cern.ch/work/a/afornara/public/xmask/example_DA_study/noise_master_study/scans/example_HL_tunescan/base_collider/xtrack_0005/run.sh &
bash /afs/cern.ch/work/a/afornara/public/xmask/example_DA_study/noise_master_study/scans/example_HL_tunescan/base_collider/xtrack_0006/run.sh &
bash /afs/cern.ch/work/a/afornara/public/xmask/example_DA_study/noise_master_study/scans/example_HL_tunescan/base_collider/xtrack_0007/run.sh &
bash /afs/cern.ch/work/a/afornara/public/xmask/example_DA_study/noise_master_study/scans/example_HL_tunescan/base_collider/xtrack_0008/run.sh &
#local_pc
