'root':
  setup_env_script: 'none'
  generations:
    1: # Build the particle distribution and base collider
      job_folder: '../../master_jobs/1_build_distr_and_collider'
      job_executable: 1_build_distr_and_collider.py # has to be a python file
      files_to_clone: # relative to the template folder
        - optics_specific_tools_hlhc15.py
      run_on: 'local_pc'
    2: # Launch the pymask and prepare the colliders
      job_folder: '../../master_jobs/2_configure_and_track'
      job_executable: 2_configure_and_track.py # has to be a python file
      files_to_clone:
        - gen_config_orbit_correction.py
        - utilsaf.py
      run_on: 'htc_GPU' # 'htc' 
      htc_job_flavor: 'microcentury' # optional parameter to define job flavor, default is espresso
  # Children will be added below in the script 001_make_folders.py
  children:

ph_noise : 15.91e-6
a_noise : 0.0 #2.0e-11
n_turns : 10